service: persona-parley

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  apiGateway:
    binaryMediaTypes:
      - '*/*'
    minimumCompressionSize: 1024
  environment:
    OPENAI_API_KEY: ${ssm:/persona-parley/OPENAI_API_KEY}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - dynamodb:PutItem
            - dynamodb:GetItem
          Resource: 
            - arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/persona-parley/*
            - !GetAtt OpenAISQSQueue.Arn
            - !GetAtt OpenAIResultsTable.Arn

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!frontend/**'
    - '!.venv/**'
    - '!__pycache__/**'
    - '!.pytest_cache/**'
    - '!tests/**'
    - '!.git/**'
    - '!*.pyc'
    - '!.DS_Store'
    - '!package.json'
    - '!package-lock.json'
    - '!README.md'
    - 'backend/**'
    - 'requirements.txt'

functions:
  api:
    handler: backend.main.lambda_handler
    timeout: 10
    memorySize: 1024
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: 'https://main.d1wv9cggx4trj9.amplifyapp.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
            allowCredentials: true
            maxAge: 86400
    environment:
      STAGE: ${sls:stage}
      SQS_QUEUE_URL: !Ref OpenAISQSQueue

  processOpenAI:
    handler: backend.process.lambda_handler
    timeout: 30
    memorySize: 1024
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - sqs:
          arn: !GetAtt OpenAISQSQueue.Arn
    environment:
      OPENAI_API_KEY: ${ssm:/persona-parley/OPENAI_API_KEY}

  getResults:
    handler: backend.get_results.lambda_handler
    timeout: 10
    memorySize: 1024
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /results/{message_id}
          method: GET
          cors: true
    package:
      patterns:
        - 'backend/**/*.py'
        - 'requirements.txt'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer:
      name: persona-parley-deps-${sls:stage}-${sls:instanceId}
    noDeploy:
      - boto3
      - botocore
      - pip
      - setuptools
      - wheel
    slim: true
    strip: true
    dockerizePip: true

resources:
  Resources:
    OpenAISQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: openai-requests-queue-${sls:stage}
        VisibilityTimeout: 60
        MessageRetentionPeriod: 1209600
        
    OpenAIResultsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: openai-results-${sls:stage}
        AttributeDefinitions:
          - AttributeName: message_id
            AttributeType: S
        KeySchema:
          - AttributeName: message_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
