service: persona-parley

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  environment:
    OPENAI_API_KEY: ${ssm:/persona-parley/OPENAI_API_KEY}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
          Resource: 
            - arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/persona-parley/*

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!frontend/**'
    - '!.venv/**'
    - '!__pycache__/**'
    - '!.pytest_cache/**'
    - '!tests/**'
    - '!.git/**'
    - '!*.pyc'
    - '!.DS_Store'
    - '!package.json'
    - '!package-lock.json'
    - '!README.md'
    - 'backend/main.py'
    - 'requirements.txt'

functions:
  api:
    handler: backend.main.lambda_handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    environment:
      STAGE: ${sls:stage}
    package:
      patterns:
        - 'backend/main.py'
        - 'requirements.txt'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer:
      name: python-deps
      description: Python dependencies for Persona Parley
    noDeploy:
      - boto3
      - botocore
    slim: false
    strip: false
    dockerizePip: true
